name: Manual test

on:
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11
  push: {}

jobs:
  build:
    uses: ./.github/workflows/main.yaml@build
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
