name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel babel
      - name: Build package
        run: |
          ./generate_setup_cfg.sh
          cp setup-library.cfg setup.cfg
          python setup.py sdist bdist_wheel
          cp setup-basic.cfg setup.cfg
          python setup.py sdist bdist_wheel
          ls -la dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
